### ISSUE TITLE
Add parameter to skip existing file for batch conversion

### ISSUE THREAD

**Issue by Technetium1** [zaytiri/handbrake-recursive-folder-video-converter#2]
Once a duplicate file is hit, it throws a python exception instead of handling it gracefully. There should be an option to skip duplicate results added.
```py
Muxing: this may take awhile...(741.28 fps, avg 706.33 fps, ETA 00h00m00s)

Encoding successfully done!

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\User\AppData\Roaming\Python\Python311\Scripts\havc.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\havc\app.py", line 36, in main
    videos.search()
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\havc\search.py", line 48, in search
    current_video_file.copy_to(sub_delete_folder)
  File "C:\Users\User\AppData\Roaming\Python\Python311\site-packages\havc\entities\video_file.py", line 51, in copy_to
    shutil.copyfile(original, target)
  File "C:\Program Files\Python311\Lib\shutil.py", line 236, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'D:\\Comedy\\Andrew Santino - Cheeseburger (2023)\\Andrew Santino - Cheeseburger (2023).mkv' and 'D:\\\\Comedy\\Andrew Santino - Cheeseburger (2023)\\Andrew Santino - Cheeseburger (2023).mkv' are the same file
```

**Comment by zaytiri** [comment]
Hello, please update your version to the new one: 1.2.0

This should now be fixed, hopefully. Please let me know if it did. Thanks!

**Comment by Technetium1** [comment]
This has skipped at least one thing so far, I assume it to be working now! Thank you!
